module.exports = {
  // Parser states
  // https://url.spec.whatwg.org/#url-parsing
  STATE_SCHEME_START: 1,
  STATE_SCHEME: 2,
  STATE_NO_SCHEME: 3,
  STATE_SPECIAL_RELATIVE_OR_AUTHORITY: 4,
  STATE_PATH_OR_AUTHORITY: 5,
  STATE_RELATIVE: 6,
  STATE_RELATIVE_SLASH: 7,
  STATE_SPECIAL_AUTHORITY_SLASHES: 8,
  STATE_SPECIAL_AUTHORITY_IGNORE_SLASHES: 9,
  STATE_AUTHORITY: 10,
  STATE_HOST: 11,
  STATE_HOSTNAME: 12,
  STATE_PORT: 13,
  STATE_FILE: 14,
  STATE_FILE_SLASH: 15,
  STATE_FILE_HOST: 16,
  STATE_PATH_START: 17,
  STATE_PATH: 18,
  STATE_OPAQUE_PATH: 19,
  STATE_QUERY: 20,
  STATE_FRAGMENT: 21
}
